apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-operator-extension
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  verbs:
  - 'list'
  - 'get'
  - 'update'
  - 'watch'
- apiGroups:
  - argoproj.io
  resources:
  - argocds/finalizers
  - argocds/status
  verbs:
  - 'update'
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-view
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - list
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-edit
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'