apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-operator-extension
subjects:
- kind: ServiceAccount
  name: argocd-operator-extension
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: argocd-operator-extension
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-operator-extension-view
subjects:
  - kind: ServiceAccount
    name: argocd-operator-extension
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: argocd-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-operator-extension-edit
subjects:
  - kind: ServiceAccount
    name: argocd-operator-extension
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: argocd-edit
  apiGroup: rbac.authorization.k8s.io