apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-helm-chart
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "resources/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-helm-templates
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "resources/templates/*").AsConfig | nindent 2 }}