kind: Secret
apiVersion: v1
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  name: cluster-kubernetes.default.svc
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  config: |-
    {
      "tlsClientConfig":{
        "insecure":false
      }
    }
  name: "in-cluster"
  {{ if .Values.admin }}
  namespaces: ""
  {{ else }}
  namespaces: "{{ .Release.Namespace }}{{- range $i, $namespace := .Values.namespaces -}},{{- $namespace -}}{{- end -}}"
  {{end}}
  server: "https://kubernetes.default.svc"
type: Opaque