kind: Secret
apiVersion: v1
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  name: cluster-kubernetes.default.svc
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  config: |-
    {
      "tlsClientConfig":{
        "insecure":false
      }
    }
  name: "in-cluster"
  namespaces: "{{ join "," .Values.namespaces }}"
  server: "https://kubernetes.default.svc"
type: Opaque